### PR TITLE
feat!: don't create subnet association

### PR DESCRIPTION
**Pull request by hknutsen**
Should be created during subnet creation instead.

### CODE REVIEW

**Review by kov117 — DISMISSED** [review]
👍🏽

**Comment by kov117** [comment]
why should subnet assocation be made during the subnet creation, and how would that be beneficial ? @hknutsen

**Comment by hknutsen** [comment]
A few reasons for this change:
1. It'll standardize the way we do subnet to NAT gateway associations. Currently you can create an association in either the [`network` module](https://github.com/equinor/terraform-azurerm-network/blob/c8a728442a5818647043f822421f91735d5ca511/main.tf#L74-L79) or this module. With this change, all associations will be created in the `network` module.
2. It'll ensure that all subnet associations are created in the [`network` module](https://github.com/equinor/terraform-azurerm-network/blob/c8a728442a5818647043f822421f91735d5ca511/main.tf#L60-L79).
3. The preifx `azurerm_subnet_*` of the Terraform resource `azurerm_subnet_nat_gateway_association` implies that it's an extension of the subnet, not the NAT gateway, thus it should be created in the `network` module, not this module.

**Comment by kov117** [comment]
sounds really good 👍🏽 and very benefical for future work as well 💯

**Review by sefornes — DISMISSED** [review]
Makes sense!

**Comment by hknutsen** [comment]
Had to update complete example to make it valid, but tests pass now 🎉 

Re-requesting review.

**Review by kov117 — APPROVED** [review]
👍🏽

**Pull request merged**
